# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/malho/Project2/project_2/project_2.cache/wt [current_project]
set_property parent.project_path D:/malho/Project2/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo d:/malho/Project2/project_2/project_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/BCDSevenSegConverter.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/ControlUnit.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/DataMemory.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/ExecuteStage.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/FullAdder.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/InstrucDecode.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/InstrucFetch.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/InstrucMemory.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/MemoryStage.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/Multiplier.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/Mux.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/RegisterFile.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/RegisterModule.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/RippleCarryFullAdder.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/WriteBackStage.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/alu4.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/alu_and.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/alu_or.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/alu_xor.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/genericDecoder.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/genericMux.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/seven_seg_controller.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/sllN.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/sraN.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/srlN.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/two_input_and.vhd
  D:/malho/Project1/LabProject/Project1/Project1.srcs/sources_1/new/MIPS_Processor.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top MIPS_Processor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MIPS_Processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MIPS_Processor_utilization_synth.rpt -pb MIPS_Processor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
