@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Apr 25 15:57:12 -0400 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim MIPS_Processor_tb_time_impl -key {Post-Implementation:sim_1:Timing:MIPS_Processor_tb} -tclbatch MIPS_Processor_tb.tcl -view D:/malho/Project2/project_2/MIPS_Processor_tb_time_impl.wcfg -view D:/malho/Project2/project_2/MIPS_Processor_tb_time_synth.wcfg -view D:/malho/Project2/project_2/MIPS_Processor_tb_behav.wcfg -log simulate.log"
call xsim  MIPS_Processor_tb_time_impl -key {Post-Implementation:sim_1:Timing:MIPS_Processor_tb} -tclbatch MIPS_Processor_tb.tcl -view D:/malho/Project2/project_2/MIPS_Processor_tb_time_impl.wcfg -view D:/malho/Project2/project_2/MIPS_Processor_tb_time_synth.wcfg -view D:/malho/Project2/project_2/MIPS_Processor_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
